### ISSUE TITLE
This mod appeared in my game

### ISSUE THREAD

**Issue by una-mura** [lucaargolo/fabric-seasons-extras#1]
I just updated Fabric Seasons to 2.0, and when I entered my world I got a notification about this add-on. I suppose that's not intended since it looks like I can't download it on modrinth or curseforge yet

**Comment by lucaargolo** [comment]
Heyy, it is intended! I was going to release all mods at the same time, but I found a bug when testing the mod in production and didn't have the time to fix it 😅. But it's already fixed and I'm releasing everything now.

**Comment by una-mura** [comment]
Ok, thanks! And olá, parceiro ;)
