### ISSUE TITLE
[1.20.1] Cant open book & crash after using Crop Detector on a block

### ISSUE THREAD

**Issue by pewblaze** [lucaargolo/fabric-seasons-extras#14]
Hi i cant open the season book in the game, nothing happens after clicking. Ive got patchouli installed.
Also i crashed after using the crop detector on a stone block. Wanted to test it what happens ^^"

My logs:
https://gist.github.com/pewblaze/b3f2944e7293749bc84fe6616f761d01

fabric-seasons-extras-1.2-BETA+1.20
Fabric 1.20.1 (0.14.21)

**Comment by CassieRoseZA** [comment]
To add onto the book Part:
https://gist.github.com/AmberRoseZA/5898e9febf35371b78ecb78f8f782f2d
this is what it throws on console upon starting up

**Comment by lucaargolo** [comment]
Hey, I tried fixing it yesterday but Patchouli was not working on the latest Fabric API version.

**Comment by qyl27** [comment]
Patchouli is working for now, and the book format should be update according to [their upgrade guide](https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120).

**Comment by lucaargolo** [comment]
This should be fixed on version 1.3.1-BETA.
