### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by Disketaa** [lucaargolo/fabric-seasons-extras#15]
Greetings! I'm working on localization but I didn't found any string that can edit "_speed_" text.
It would also be nice to see a config to disable some features. Personally, I prefer original compact tooltips over percentage ones.

![image](https://github.com/lucaargolo/fabric-seasons-extras/assets/76956762/56ef1f68-ecc5-4193-9fa8-5a159b56ba9e)

**Comment by mpustovoi** [comment]
It's a core Fabric Seasons mod issue.
I'll make a PR to fix this.
