### ISSUE TITLE
Seasonal Compendium doesn't Work

### ISSUE THREAD

**Issue by DumbXBoxAcct** [lucaargolo/fabric-seasons-extras#26]
Nothing happens when I hold the book and "use" it by right-clicking.  I believe that someone else had this problem last year too (#14 Can't Open Book & Crash...) and you may have been able to fix it by updating the Patchouli book, so I'm hoping that just another quick update is required.  I've attached the log showing the error message, which is:

"Failed to load book seasonsextras:seasonal_compendium defined by mod seasonsextras, skipping
java.lang.IllegalArgumentException: Book seasonsextras:seasonal_compendium has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.

For reference, I'm using the latest version of the mod - 1.2-Beta - with MC 1.20.1 and Fabric Loader 0.5.11.  

[latest.log](https://github.com/user-attachments/files/16007724/latest.log)

**Comment by lucaargolo** [comment]
This should be fixed on version 1.3.1-BETA.

**Comment by DumbXBoxAcct** [comment]
Works great!  Thank you, Luca!
