### ISSUE TITLE
Textures no longer have mipmapping

### ISSUE THREAD

**Issue by Reyks21** [lucaargolo/fabric-seasons-extras#4]
For some reason mipmapping stops working when this mod is installed, very noticeable on leaf blocks.

**Comment by xR4YM0ND** [comment]
Very important, pls fix asap

Here's a latest.log where `seasonsextras:block/calendar/summer_9` limits mip level from 2 to 0
[latest.log](https://gist.github.com/xR4YM0ND/5d26fadf245d0d161aba5d8be91702ea) - check line 1016

PS:
Don't mind another_furniture which has the same problem...
