### ISSUE TITLE
Calendar crashing the game

### ISSUE THREAD

**Issue by nvb-uy** [lucaargolo/fabric-seasons-extras#6]
The calendar is crashing the game when ticking. This is from the Prominence FABRIC Modpack.

Log: https://mclo.gs/HNCRn2F

**Comment by SolacianAllie** [comment]
Having the same issue, every time the calendar is placed the server has a heart attack and closes

**Comment by lucaargolo** [comment]
This issue should be fixed by updating Fabric Seasons to version 2.2.1.
