### ISSUE TITLE
Crash when placing block of Season Calendar

### ISSUE THREAD

**Issue by JackLas** [lucaargolo/fabric-seasons-extras#7]
Minecraft 1.19.2 + Fabric 0.14.21
fabric-seasons-2.2+1.19.jar 
fabric-seasons-extras-1.2-BETA+1.19.jar 

Tried to place Season Calendar and then get crash.
Logs available here: https://pastebin.com/v2SQtMAN

**Comment by lucaargolo** [comment]
Update Fabric Seasons to version 2.2.1
